### ISSUE TITLE
Random null reference errors at PodioAPI.Podio.Request[T]

### ISSUE THREAD

**Issue by aztommylee** [podio/podio-dotnet#43]
Using NuGet Podio.Net package version 1.5.6

Doesn't seem to be a rhyme or reason to it, but we are getting occasional NullRefenceExceptions in the Request method after calling AddItem or UpdateItem.  Is there a way to build the Non-Async version of Podio.net to debug further?  Unless I'm missing something, the repository only contains async code.

> System.NullReferenceException: **Object reference not set to an instance of an object**.
>    at PodioAPI.Podio.Request[T](RequestMethod requestMethod, String url, Object requestData, Object options)
>    at PodioAPI.Podio.Put[T](String url, Object requestData, Object options)
>    at PodioAPI.Services.ItemService.UpdateItem(Item item, Nullable`1 spaceId, Nullable`1 revision, Boolean silent, Boolean hook)
>    at RAPodioLib.RAPodioAPI.InsertUpdateAgentContact(Podio podio, Property property, DataTable agentData, DataTable brokerData) in D:\LocalGit\PodioLib\RAPodioAPI.cs:line 556

> System.NullReferenceException: **Object reference not set to an instance of an object.**
>    at PodioAPI.Podio.Request[T](RequestMethod requestMethod, String url, Object requestData, Object options)
>    at PodioAPI.Podio.Post[T](String url, Object requestData, Object options)
>    at PodioAPI.Services.ItemService.AddNewItem(Int32 appId, Item item, Nullable`1 spaceId, Boolean silent, Boolean hook)
>    at RAPodioLib.RAPodioAPI.InsertUpdateProperty(Podio podio, Property property, Int32 mlsPhotoID) in D:\LocalGit\PodioLib\RAPodioAPI.cs:line 315
>

**Comment by AjmalVh** [comment]
The v1 branch have the synchronous code.

**Comment by clarkd** [comment]
We seem to be experiencing a similar issue (same exception stack) but from PodioAPI.Podio.Authenticate

**Comment by regnerhenrique** [comment]
Hello, I'm also having the same problem in AuthenticateWithApp, I made the project clone and debugging it hangs on the HttpClient.SendAsync (httpRequest) call in the Request <T> method in Podio.cs

**Comment by clarkd** [comment]
For me, it was caused by Podio recently switching to TLS 1.1. ensure you
are using version 1.1 or higher.

**Comment by regnerhenrique** [comment]
Ohhh @clarkd you resolved the problem! Thanks very much, my friend.

**Comment by clarkd** [comment]
No problem, took me a while to figure out. The Podio exception is useless!
We recently had a similar issue with another API so I took a wild guess!

**Comment by myktra** [comment]
FWIW, we have an application built on an older version of the .NET Framework (4.5) on an isolated workstation and were experiencing the same issues. After applying some registry settings we were able to get a workaround in place to force the application to use safer versions of TLS.

See:

https://docs.microsoft.com/en-us/dotnet/framework/network-programming/tls
https://docs.microsoft.com/en-us/dotnet/framework/network-programming/tls#configuring-security-via-the-windows-registry

Specifically we added the two registry entries mentioned in the second article, `SchUseStrongCrypto` and `SystemDefaultTlsVersions`.

HTH!

**Comment by muikka** [comment]
you should set your framawork target to 4.7 and above.
it will work bcs of security features :)

**Comment by abhipadm** [comment]
Podio disabled the TLS 1.0  in July 2018. Please see the below thread:
https://stackoverflow.com/questions/51216043/podio-an-existing-connection-was-forcibly-closed-by-the-remote-host/51229955#51229955
